/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            fontFamily: {
                display: ['Playfair Display', 'Georgia', 'serif'],
                sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
                mono: ['JetBrains Mono', 'SF Mono', 'Menlo', 'Consolas', 'monospace'],
            },
            colors: {
                primary: '#FF5A1F',
                'primary-deep': '#E04A10',
                sunshine: {
                    300: '#FFD699',
                    500: '#FFB366',
                    700: '#FF8C33',
                    800: '#E67300',
                    900: '#CC5A00',
                },
                'yellow-saturated': '#FFD700',
                cream: '#FFF8F0',
                'cream-soft': '#FFFBF5',
                'cream-deeper': '#FFEEDD',
                'beige-deep': '#E8D5C4',
                canvas: '#FFFFFF',
                surface: '#F8F6F4',
                'surface-cream': '#FFF8F0',
                'surface-code': '#1A1A2E',
                hairline: '#E5E0DB',
                'hairline-soft': '#EDE8E3',
                'hairline-strong': '#C8C0B8',
                ink: '#0A0A0A',
                'ink-tint': 'rgba(10, 10, 10, 0.75)',
                charcoal: '#333333',
                slate: '#666666',
                steel: '#999999',
                stone: '#B0B0B0',
                muted: '#CCCCCC',
                'on-dark': '#FFFFFF',
                'on-dark-muted': 'rgba(255, 255, 255, 0.7)',
                'on-cream': '#0A0A0A',
                link: '#FF5A1F',
                'footer-cream': '#FFF8F0',
            },
            borderRadius: {
                xs: '4px',
                sm: '6px',
                md: '8px',
                lg: '12px',
                xl: '16px',
                xxl: '20px',
            },
            fontSize: {
                'hero-display': ['84px', { lineHeight: '1.05', letterSpacing: '-1.5px' }],
                'display-lg': ['64px', { lineHeight: '1.10', letterSpacing: '-1px' }],
                'heading-1': ['52px', { lineHeight: '1.15', letterSpacing: '-0.5px' }],
                'stat-display': ['56px', { lineHeight: '1.10', letterSpacing: '-1px' }],
                'heading-2': ['36px', { lineHeight: '1.20', letterSpacing: '-0.5px' }],
                'heading-3': ['28px', { lineHeight: '1.25', letterSpacing: '0' }],
                'heading-4': ['22px', { lineHeight: '1.30', letterSpacing: '0' }],
                'heading-5': ['18px', { lineHeight: '1.40', letterSpacing: '0' }],
                'subtitle': ['18px', { lineHeight: '1.50' }],
                'body-md': ['16px', { lineHeight: '1.55' }],
                'body-md-medium': ['16px', { lineHeight: '1.55' }],
                'body-sm': ['14px', { lineHeight: '1.50' }],
                'body-sm-medium': ['14px', { lineHeight: '1.50' }],
                'caption': ['13px', { lineHeight: '1.40' }],
                'caption-bold': ['13px', { lineHeight: '1.40' }],
                'micro': ['12px', { lineHeight: '1.40' }],
                'micro-uppercase': ['11px', { lineHeight: '1.40', letterSpacing: '1px' }],
                'button-md': ['14px', { lineHeight: '1.30' }],
                'code-md': ['14px', { lineHeight: '1.50' }],
            },
            spacing: {
                xxs: '4px',
                xs: '8px',
                'section-sm': '48px',
                section: '64px',
                'section-lg': '96px',
                hero: '120px',
            },
            boxShadow: {
                subtle: '0px 1px 2px 0px rgba(0, 0, 0, 0.04)',
                card: '0px 4px 12px 0px rgba(0, 0, 0, 0.04)',
                mockup: '0px 12px 24px -4px rgba(0, 0, 0, 0.08)',
                modal: '0px 16px 48px -8px rgba(0, 0, 0, 0.12)',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};